language: python
python:
  - "3.6"
# command to install dependencies
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install -r requirements.txt

script: python3 ML.py --cov=Protein-feature-extraction
  - coverage run ML.py

after_success:
  - codecov
