language: python
python:
  - "3.6"
# command to install dependencies
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
install:
  - pip install -r requirements.txt
  - pip install cython

script: pytest
